[package]
name = "protorpc"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
bytes = "1.10.1"
futures-core = "0.3.31"
prost = "0.14.1"
lru = "0.16.0"
rand = "0.9.2"
nanoid = "0.4.0"
thiserror = "2.0.12"
tokio-stream = "0.1.17"
log = { version = "0.4.27", optional = true }
tokio = { version = "1", features = [
    "io-util",
    "macros",
    "sync",
    "time",
    "rt",
] }

[build-dependencies]
prost-build = { version = "0.14", features = ["cleanup-markdown"] }

[features]
log = ["dep:log"]
