[package]
name = "protorpc-build"
version = "0.1.0"
edition = "2024"

[dependencies]
quote = "1.0.40"
syn = "2.0"
proc-macro2 = "1.0"
prettyplease = "0.2.35"
prost-build = { version = "0.14", features = ["cleanup-markdown"] }
