name: tests
on:
    push:
        branches:
            - main
        paths:
            - protorpc/**
            - protorpc-build/**
            - tests/**
            - Cargo.toml
            - Cargo.lock
    pull_request:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
            - name: Install Protoc
              uses: arduino/setup-protoc@v3
            - name: Run tests
              run: cargo test
            - name: Run check for wasm32
              run: |
                  rustup target add wasm32-unknown-unknown
                  cargo check --target wasm32-unknown-unknown
